import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'hrms',
        path: '',
        title: 'HRMS',
        translateKey: 'nav.hrms.title',
        icon: 'usersIcon',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'hrms.item1',
                path: '/employees',
                title: 'Employee',
                translateKey: 'nav.hrms.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

    

    // {
    //     key: 'cms',
    //     path: '',
    //     title: 'CMS',
    //     translateKey: 'nav.cms.title',
    //     icon: 'fileTextIcon',
    //     type: NAV_ITEM_TYPE_COLLAPSE,
    //     authority: [],
    //     subMenu: [
    //         {
    //             key: 'cms.item1',
    //             path: '/content-categories',
    //             title: 'Content Categories',
    //             translateKey: 'nav.cms.item1',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'cms.item2',
    //             path: '/contents',
    //             title: 'Contents',
    //             translateKey: 'nav.cms.item2',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //         {
    //             key: 'cms.item2',
    //             path: '/contentasset',
    //             title: 'Content Assets',
    //             translateKey: 'nav.cms.item3',
    //             icon: '',
    //             type: NAV_ITEM_TYPE_ITEM,
    //             authority: [],
    //             subMenu: [],
    //         },
    //     ],
    // },
    {
        key: 'crm',
        path: '',
        title: 'CRM',
        translateKey: 'nav.crm.title',
        icon: 'contactsIcon',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            // {
            //     key: 'contact',
            //     path: '/contact',
            //     title: 'Contacts',
            //     translateKey: 'nav.crm.item1',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     authority: [],
            //     subMenu: [],
            // },
            {
                key: 'enquiries',
                path: '/enquiries',
                title: 'Enquiries',
                translateKey: 'nav.crm.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'assets',
        path: '',
        title: 'ASSETS',
        translateKey: 'nav.assets.title',
        icon: 'boxIcon',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'assettypes',
                path: '/assettypes',
                title: 'Asset Types',
                translateKey: 'nav.assets.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'assets',
                path: '/assets',
                title: 'Assets',
                translateKey: 'nav.assets.item2',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'assetcategories',
                path: '/assetcategories',
                title: 'Asset Categories',
                translateKey: 'nav.assets.item3',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'asset_type_categories',
                path: '/asset_type_categories',
                title: 'Asset Type Categories',
                translateKey: 'nav.assets.item4',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'orderform',
        path: '/order',
        title: 'ORDER',
        translateKey: 'nav.crm.title',
        icon: 'orderIcon',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'orderform',
                path: '/order',
                title: 'Orders',
                translateKey: 'nav.crm.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
             {
                key: 'Zones',
                path: '/zone',
                title: 'Zones',
                translateKey: 'nav.crm.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'Organizations',
                path: '/organization',
                title: 'Organizations',
                translateKey: 'nav.crm.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'Delivery',
                path: '/delivery',
                title: 'Delivery',
                translateKey: 'nav.crm.item1',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
        {
        key: 'participate',
        path: '',
        title: 'Events',
        translateKey: 'nav.eventmanagement.title',
        icon: 'eventsIcon',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'events',
                path: '/events',
                title: 'Events',
                translateKey: 'nav.events.item1',
                icon: 'MdEvent',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'participate',
                path: '/participants',
                title: 'Participants',
                translateKey: 'nav.participate.item1',
                icon: 'MdEvent',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },

]

export default navigationConfig
